name: poc
kind: Project
backend: default
variables:
  organization: ortelius
  domain: "cluster.dev"
#exports:
#  AWS_PROFILE: cluster-dev # optional set the AWS profile to use during apply
#  CDEV_TF_BINARY: /usr/local/bin/terraform-0.14.9 # optional set of TF version
